name: Feature Request
description: Suggest an idea for this extension
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! This is a free, open source extension. Feature requests will be evaluated based on user value and community benefit.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Essential for my use case
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Which best describes your usage?
      options:
        - Casual YouTube viewer
        - Content creator
        - Power user (heavy YouTube usage)
        - Developer/Technical user
        - Accessibility user
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: How would this feature improve your YouTube experience?
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
      placeholder: Any additional information, screenshots, or examples that might help explain the request.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these before submitting
      options:
        - label: I have checked existing feature requests for duplicates
          required: true
        - label: This feature is related to YouTube blur/glow removal or UI enhancement
          required: true
        - label: I understand this is an open source extension and feature implementation depends on community interest and feasibility
          required: true
